"""add handbook tables

Revision ID: 2985f08cea00
Revises: c4b2db2ff29b
Create Date: 2026-06-04 13:58:11.772933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2985f08cea00'
down_revision: Union[str, Sequence[str], None] = 'c4b2db2ff29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hb_countries')
    with op.batch_alter_table('hb_changelog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hb_changelog_created'))
        batch_op.drop_index(batch_op.f('ix_hb_changelog_entity'))

    op.drop_table('hb_changelog')
    with op.batch_alter_table('hb_news_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hb_news_links_article'))
        batch_op.drop_index(batch_op.f('ix_hb_news_links_gen_news'))

    op.drop_table('hb_news_links')
    with op.batch_alter_table('hb_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hb_persons_country'))
        batch_op.drop_index(batch_op.f('ix_hb_persons_org_unit'))

    op.drop_table('hb_persons')
    with op.batch_alter_table('hb_org_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hb_org_units_country'))
        batch_op.drop_index(batch_op.f('ix_hb_org_units_parent'))

    op.drop_table('hb_org_units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hb_org_units',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('country_id', sa.VARCHAR(), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=400), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('unit_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('legal_basis', sa.TEXT(), nullable=True),
    sa.Column('resources', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('valid_from', sa.DATETIME(), nullable=True),
    sa.Column('valid_to', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['hb_countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['hb_org_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hb_org_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hb_org_units_parent'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hb_org_units_country'), ['country_id'], unique=False)

    op.create_table('hb_persons',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('org_unit_id', sa.VARCHAR(), nullable=True),
    sa.Column('country_id', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('patronymic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('position_title', sa.VARCHAR(length=400), nullable=True),
    sa.Column('rank', sa.VARCHAR(length=200), nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('contacts', sqlite.JSON(), nullable=True),
    sa.Column('resources', sqlite.JSON(), nullable=True),
    sa.Column('date_appointed', sa.DATETIME(), nullable=True),
    sa.Column('date_dismissed', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['hb_countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['hb_org_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hb_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hb_persons_org_unit'), ['org_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hb_persons_country'), ['country_id'], unique=False)

    op.create_table('hb_news_links',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('article_id', sa.VARCHAR(), nullable=True),
    sa.Column('generated_news_id', sa.VARCHAR(), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('country_id', sa.VARCHAR(), nullable=True),
    sa.Column('org_unit_id', sa.VARCHAR(), nullable=True),
    sa.Column('person_id', sa.VARCHAR(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('pinned_by', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['hb_countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['hb_org_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['hb_persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'entity_type', 'country_id', 'org_unit_id', 'person_id', name=op.f('uq_hb_news_link'))
    )
    with op.batch_alter_table('hb_news_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hb_news_links_gen_news'), ['generated_news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hb_news_links_article'), ['article_id'], unique=False)

    op.create_table('hb_changelog',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('country_id', sa.VARCHAR(), nullable=True),
    sa.Column('org_unit_id', sa.VARCHAR(), nullable=True),
    sa.Column('person_id', sa.VARCHAR(), nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=200), nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('old_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('diff', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['hb_countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['hb_org_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['hb_persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hb_changelog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hb_changelog_entity'), ['entity_type', 'country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hb_changelog_created'), ['created_at'], unique=False)

    op.create_table('hb_countries',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=4), nullable=False),
    sa.Column('name_uk', sa.VARCHAR(length=200), nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=200), nullable=False),
    sa.Column('flag_emoji', sa.VARCHAR(length=8), nullable=True),
    sa.Column('capital', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('resources', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
