"""add minhash signatures table

Revision ID: d073f8ba8709
Revises: 
Create Date: 2026-05-13 10:06:51.439899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd073f8ba8709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minhash_signatures',
    sa.Column('raw_article_id', sa.String(length=36), nullable=False),
    sa.Column('signature', sa.JSON(), nullable=False),
    sa.Column('num_perm', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('raw_article_id')
    )
    with op.batch_alter_table('minhash_signatures', schema=None) as batch_op:
        batch_op.create_index('ix_minhash_created', ['created_at'], unique=False)

    with op.batch_alter_table('feed_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_feed_item_article', ['snapshot_id', 'article_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_feed_item_article', type_='unique')

    with op.batch_alter_table('minhash_signatures', schema=None) as batch_op:
        batch_op.drop_index('ix_minhash_created')

    op.drop_table('minhash_signatures')
    # ### end Alembic commands ###
